# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Ui_memory.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Mem(object):
    def setupUi(self, Dialog_Mem):
        Dialog_Mem.setObjectName("Dialog_Mem")
        Dialog_Mem.resize(532, 378)
        self.memory_content = QtWidgets.QTextBrowser(Dialog_Mem)
        self.memory_content.setGeometry(QtCore.QRect(9, 9, 521, 331))
        self.memory_content.setObjectName("memory_content")
        self.mem_content_clear = QtWidgets.QPushButton(Dialog_Mem)
        self.mem_content_clear.setGeometry(QtCore.QRect(370, 350, 75, 23))
        self.mem_content_clear.setObjectName("mem_content_clear")
        self.mem_content_cancel = QtWidgets.QPushButton(Dialog_Mem)
        self.mem_content_cancel.setGeometry(QtCore.QRect(450, 350, 75, 23))
        self.mem_content_cancel.setObjectName("mem_content_cancel")

        self.retranslateUi(Dialog_Mem)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Mem)

    def retranslateUi(self, Dialog_Mem):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Mem.setWindowTitle(_translate("Dialog_Mem", "查找"))
        self.mem_content_clear.setText(_translate("Dialog_Mem", "清除"))
        self.mem_content_cancel.setText(_translate("Dialog_Mem", "取消"))
