# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Ui_querydialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Query(object):
    def setupUi(self, Dialog_Query):
        Dialog_Query.setObjectName("Dialog_Query")
        Dialog_Query.resize(488, 80)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\X.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_Query.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_Query)
        self.gridLayout.setObjectName("gridLayout")
        self.ValueQuery_line = QtWidgets.QLineEdit(Dialog_Query)
        self.ValueQuery_line.setObjectName("ValueQuery_line")
        self.gridLayout.addWidget(self.ValueQuery_line, 0, 0, 1, 2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Query_Button = QtWidgets.QPushButton(Dialog_Query)
        self.Query_Button.setObjectName("Query_Button")
        self.verticalLayout.addWidget(self.Query_Button)
        self.Query_addr_Button = QtWidgets.QPushButton(Dialog_Query)
        self.Query_addr_Button.setObjectName("Query_addr_Button")
        self.verticalLayout.addWidget(self.Query_addr_Button)
        self.gridLayout.addLayout(self.verticalLayout, 0, 2, 2, 1)
        self.ValueQureyAddr_line = QtWidgets.QLineEdit(Dialog_Query)
        self.ValueQureyAddr_line.setObjectName("ValueQureyAddr_line")
        self.gridLayout.addWidget(self.ValueQureyAddr_line, 1, 0, 1, 1)
        self.QueryAddrLen_line = QtWidgets.QLineEdit(Dialog_Query)
        self.QueryAddrLen_line.setObjectName("QueryAddrLen_line")
        self.gridLayout.addWidget(self.QueryAddrLen_line, 1, 1, 1, 1)

        self.retranslateUi(Dialog_Query)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Query)

    def retranslateUi(self, Dialog_Query):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Query.setWindowTitle(_translate("Dialog_Query", "查找"))
        self.ValueQuery_line.setPlaceholderText(_translate("Dialog_Query", "输入变量名或者函数名"))
        self.Query_Button.setText(_translate("Dialog_Query", "查询变量"))
        self.Query_addr_Button.setText(_translate("Dialog_Query", "查询地址"))
        self.ValueQureyAddr_line.setPlaceholderText(_translate("Dialog_Query", "输入地址（16进制)"))
        self.QueryAddrLen_line.setPlaceholderText(_translate("Dialog_Query", "字节长度（默认512字节）"))
